### ISSUE TITLE
How would you go about generating a PDF file with this library?

### ISSUE THREAD

**Issue by mrkkrp** [Yuras/pdf-toolbox#32]
There seems to be no alternatives to this package, and we need to generate PDF at work. Currently we make an HTML file and feed it into an external command line tool called `wkhtmltopdf`, which is really ugly, as you could tell.

I looked through the Haddocks and examples, but it's still not clear how you generate PDF files with this library. Can you help by showing a basic example?

**Comment by Yuras** [comment]
Did you see [this example](https://github.com/Yuras/pdf-toolbox/blob/stable/examples/create-simple-pdf-file.hs)? It is low level, but there is nothing better right now. I created the library because I wanted to edit existing PDF files, generating new files was not a goal. There is also [hpdf](http://hackage.haskell.org/package/HPDF)

**Comment by mrkkrp** [comment]
I somehow missed that example, blind me! Thanks. I'll take a look at `hpdf` too.
