### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by tysonzero** [Yuras/pdf-toolbox#42]
I was curious if there would be a hackage release anytime soon. I would greatly appreciate one assuming you consider things to be reasonably stable/working.

**Comment by Yuras** [comment]
Well, it is not stable enough I guess... I started API refactoring but never finished it. This library it not well maintained, sorry.

**Comment by tysonzero** [comment]
No worries! This library has been incredibly useful and I appreciate it a lot!

**Comment by cartazio** [comment]
let me know if theres any way i can cheerlead stuff along :)

**Comment by Yuras** [comment]
@cartazio I guess I have to release whatever I have right now :)
I'll try to upload in to hackage this week.

**Comment by coderfromhere** [comment]
I'm interested in a new release as well, what needs to be done to make it happen?

**Comment by Yuras** [comment]
Yeah, I failed to keep the promise. Sorry for that.

The plain could look like that:

- [X]  Setup CI (travis is dead?)
- [ ] Land #59, probably via #69 
- [ ] Cleanup haddock (I saw a number of warnings here)
- [ ] Cut the release
- [ ] Profit?

Also ghc-9 won't work yet because of https://github.com/snapframework/io-streams/issues/76

@coderfromhere  I guess feedback is the only motivation that actually works for me :) So are you using this code for anything specific? Is it for a hobby project or something commercial?

Also why hackage release is necessary for you? I mean you can use the packages from the repository directly.

**Comment by avanov** [comment]
@Yuras Hi! Above was my work account. I'm interested because I have a proof-of-concept utility in mind at work that could alternatively be implemented with a Python toolchain, but I'd rather not go that direction before trying Haskell first :) Something about fulltext search.

A Hackage release is helpful because eventually it automatically gets into official Nix builds that could be downloaded as a cached object from the official binary cache - https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/hackage-packages.nix - and my Nix pipelines would require fewer customly written overlays for external packages.

**Comment by cartazio** [comment]
I’ve some head space to help hack on this if needed.

Shoot  me an email if there’s any bits a good PR can address :)

**Comment by avanov** [comment]
@cartazio thanks!

**Comment by Yuras** [comment]
[Here](https://hackage.haskell.org/package/pdf-toolbox-core-0.1.1) [we](https://hackage.haskell.org/package/pdf-toolbox-content-0.1.1) [go](https://hackage.haskell.org/package/pdf-toolbox-document-0.1.1)! Finally closing this issue.

**Comment by avanov** [comment]
@Yuras brilliant! thank you
